name: my_pgp mirror CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  TARGET_REPO_URL: "git@github.com:EpitechPGE3-2026/G-ING-500-NAN-5-1-rtype-3.git"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # futur jobs tests ...
  #   name: ...
  #   if: ${{ github.repository == 'Matt4401/Mirror-Rtype' }}
  #   runs-on: ubuntu-latest
    

  push_to_mirror:
    name: Push to target repository
    if: ${{ github.repository == 'Matt4401/Mirror-Rtype' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.TARGET_REPO_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }} # link to matt repo